kind: KubeSchedulerConfiguration
apiVersion: kubescheduler.config.k8s.io/v1
extenders:
  - urlPrefix: "http://localhost:8080/"
    prioritizeVerb: "priorities"
    weight: 1
    enableHTTPS: false
    nodeCacheCapable: false